#!/bin/python
# \
import sdds,sys
x= sdds.SDDS(0)
x.load("phase_adv.fin")
print(x.parameterData[39])
#print("______________________________________________________________________________")
#print(x.columnData[1])
#print("______________________________________________________________________________")
#print(x.columnData[2])
#print("______________________________________________________________________________")
#print(x.columnData[3])

